menu:
  keppler_cv:
    name: Keppler Cv
    current: ['/']
    url_path: /
    icon: layers
    model: User
    submenu:
      - certificate:
          name: certificates
          url_path: /admin/cv/certificates
          icon: layers
          current: ['/admin/cv/certificates']
          model: KepplerCv::Certificate

      - testimonial:
          name: testimonials
          url_path: /admin/cv/testimonials
          icon: layers
          current: ['/admin/cv/testimonials']
          model: KepplerCv::Testimonial

      - project:
          name: projects
          url_path: /admin/cv/projects
          icon: layers
          current: ['/admin/cv/projects']
          model: KepplerCv::Project

      - language:
          name: languages
          url_path: /admin/cv/languages
          icon: layers
          current: ['/admin/cv/languages']
          model: KepplerCv::Language

      - new:
          name: + Add new module
          url_path: /url_path
          current: ['/current_path']
          enviroment: development
          model: User