modules:
  testimonials:
    name: Testimonial
    model: KepplerCvTestimonial
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  projects:
    name: Project
    model: KepplerCvProject
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  languages:
    name: Language
    model: KepplerCvLanguage
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]
