---
- id: 1
  name: keppler
  url: "/keppler"
  method: GET
  active: true
  format_result: HTML
  position: 1
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-10 17:23:16.614075000 Z
    zone: &1 !ruby/object:ActiveSupport::TimeZone
      name: America/Caracas
    time: 2018-10-10 13:23:16.614075000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-10 17:23:16.614075000 Z
    zone: *1
    time: 2018-10-10 13:23:16.614075000 Z
- id: 2
  name: index
  url: "/"
  method: GET
  active: true
  format_result: HTML
  position: 2
  deleted_at: 
  created_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-10 17:29:05.125284000 Z
    zone: *1
    time: 2018-10-10 13:29:05.125284000 Z
  updated_at: !ruby/object:ActiveSupport::TimeWithZone
    utc: 2018-10-10 17:29:05.125284000 Z
    zone: *1
    time: 2018-10-10 13:29:05.125284000 Z
